### ISSUE TITLE
Best hyperparams command for retrain

### ISSUE THREAD

**Issue by xmangaz** [bdi-lab/InGram#1]
Hello, 

Thank you for cool work! do you have hyperparameter setting (arguments) for your best models produced for all datasets? Is there bash script to retrain and reproduce? 

Thanks!!! :)

**Comment by jaejunlee714** [comment]
Hello,

Thanks for your interest in our work!
You can find the hyperparameter setting we used to produce our best results in the provided ckpt.zip file.
I'm sorry that we do not have a bash script for retraining and reproducing. As we wrote in the 'training from scratch' section of the readme file, please tune the hyperparameters of our model using the range provided in Appendix C of the paper because the best hyperparameters may be different due to randomness and hardware differences. 
Thank you!

Best,
Jaejun Lee

**Comment by xmangaz** [comment]
Oh perfect,, I See now there is config.json! 

many THanks!!
