### ISSUE TITLE
About Semi-Inductive Datasets

### ISSUE THREAD

**Issue by spankeran** [bdi-lab/InGram#5]
Hi, thanks for sharing your codes. I'm trying to run your code on semi-inductive datasets, e.g.,, FB15k-237 (v1-v4). However the results I got were very poor.  I notice that in your paper, InGram achieves salient performance on NELL-995-v1.  Are there any special settings required when conducting this kind of experiment?

**Comment by jaejunlee714** [comment]
Hello,

Thanks for your interest in our work!
For NELL-995-v1, we validated the performance with the valid.txt in the _ind folder, including the baselines.
So, for other semi-inductive datasets, e.g., FB15k-237 (v1-v4), validating the performance with the valid.txt in the _ind folder instead of the one from the train folder would help.
Thank you.

Best,
Jaejun Lee

**Comment by spankeran** [comment]
Thanks for your reply! I will try it.
